import styles from "@/styles/account.module.css";
import LoginHeader from "./components/loginheader";
import React, { useState, useEffect, ChangeEvent } from "react";
import type { Perfil } from "@/services/services";
import Head from "next/head";
import MenuMobile from "./components/menumobile";

export default function Account() {
  const [perfil, setPerfil] = useState<Perfil | null>(null);

  useEffect(() => {
    const fetchPerfil = async () => {
      try {
        const response = await fetch("/api/usuario/perfil");
        if (response.ok) {
          const data = await response.json();
          setPerfil(data);
        } else {
          console.log("Erro ao obter perfil:", response.status);
        }
      } catch (error) {
        console.log("Erro ao obter perfil:", error);
      }
    };
    fetchPerfil();
  }, []);

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault()

    try {
        const {nome, idade, telefone, endereco} = event.currentTarget.elements as any;
        const body = JSON.stringify({nome: nome.value, idade: parseInt(idade.value), telefone: telefone.value, endereco: endereco.value});

        const response = await fetch('/api/usuario/perfil', {
            method: 'PATCH',
            headers: {
                'Content-Type': 'application/json',
            },
            body,
        });
        if (response.ok) {
            const data = await response.json();
            setPerfil(data);
        } else {
            console.log('Erro ao atualizar o perfil: ', response.status);
        }
        alert('Usuário atualizado')
    } catch (error){
        console.log('Erro ao atualizar o perfil:', error)
    }
  };

  const handleInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    const { name, value } = event.target;
    setPerfil(prevPerfil => ({
      ...prevPerfil,
      [name]: value !== "" ? value : "",
    }) as Perfil);
  };
  
  
  return (
    <>
      <Head>
        <title>Minha conta</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <LoginHeader/>
        <section>
          <div>
            <form className={styles.forms} onSubmit={handleSubmit}>
              <div className={styles.menu}>
                <h1>Minha conta</h1>
                <button type="submit">Editar</button>
              </div>
              <div>
              <input
                  type="text"
                  placeholder="Nome completo"
                  value={perfil?.nome || ""}
                  onChange={handleInputChange}
                  name="nome"
                />
              </div>
              <div>
                <input
                  type="email"
                  placeholder="email@example.com"
                  value={perfil?.email || ""}
                  onChange={handleInputChange}
                  name="email"
                  readOnly
                />
              </div>
              <div className={styles.size}>
                <input
                  type="text"
                  placeholder="000.000.000-00"
                  value={perfil?.cpf || ""}
                  onChange={handleInputChange}
                  name="cpf"
                  readOnly
                />
                <input
                  type="number"
                  placeholder="Idade"
                  min="0"
                  value={perfil?.idade || ""}
                  onChange={handleInputChange}
                  name="idade"
                />
              </div>
              <div className={styles.size}>
                <input
                  type="text"
                  placeholder="(00) 00000-0000"
                  value={perfil?.telefone || ""}
                  onChange={handleInputChange}
                  name="telefone"
                />
              </div>
              <div>
                <input
                  type="text"
                  placeholder="Endereço"
                  value={perfil?.endereco || ""}
                  onChange={handleInputChange}
                  name="endereco"
                />
              </div>
            </form>
          </div>
        </section>
        <MenuMobile/>
      </main>
    </>
  );
}
