import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/atracoes.module.css'
import Header from './components/header'

export default function Home() {
  return (
    <>
      <Head>
        <title>AfroPunk - Atrações</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <section className={styles.section}>
            <div className={styles.top}>
                <div id={styles.linhatop}></div>
                <div className={styles.toptext}>
                    <div className={styles.toptexta}>
                        <a href="/">Voltar</a>
                    </div>
                    <div className={styles.toptexth1}>
                        <h1>Atrações</h1>                        
                    </div>
                </div>
                <div id={styles.linhabottom}></div>
            </div>
            <div className={styles.bottom}>
                <div className={styles.column}>
                    <h2>17 novembro</h2>
                    <div className={styles.colunas}>
                        <div className={styles.card}>
                                <p>18:00</p>
                                <h3>DJ Tamy</h3>
                            </div>
                        <div className={styles.cardimpar}>
                            <div className={styles.card}>
                                <p>19:00</p>
                                <h3>Nic Dias</h3>
                            </div> 
                        </div>
                        <div className={styles.card}>
                            <p>20:00</p>
                            <h3>Psirico</h3>
                        </div>
                        <div className={styles.cardimpar}>
                            <div className={styles.card}>
                                <p>21:00</p>
                                <h3>Liniker</h3>
                            </div>
                        </div>
                        <div className={styles.card}>
                            <p>22:00</p>
                            <h3>Yan Cloud</h3>
                        </div>
                        <div className={styles.cardimpar}>
                            <div className={styles.card}>
                                <p>23:00</p>
                                <h3>Emicida</h3>
                            </div>
                        </div>
                        <div className={styles.card}>
                            <p>00:00</p>
                            <h3>Djonga</h3>
                        </div>
                        <div className={styles.cardimpar}>
                            <div className={styles.card}>
                                <p>01:00</p>
                                <h3>Margareth Menezes</h3>
                            </div>
                        </div>
                        <div className={styles.card}>
                            <p>02:00</p>
                            <h3>Paulilo Paredão</h3>
                        </div>
                        <div className={styles.cardimpar}>
                            <div className={styles.card}>
                                <p>03:00</p>
                                <h3>Dawer</h3>
                            </div> 
                        </div>
                    </div>                    
                </div>
                <div id={styles.linhacenter}></div>
                <div className={styles.column}>
                    <h2>18 novembro</h2>
                    <div className={styles.colunas}>
                            <div className={styles.card}>
                                <p>18:00</p>
                                <h3>DJ Tamy</h3>
                            </div>
                            <div className={styles.cardimpar}>
                                <div className={styles.card}>
                                    <p>19:00</p>
                                    <h3>N.I.N.A</h3>
                                </div>
                            </div>                            
                            <div className={styles.card}>
                                <p>20:00</p>
                                <h3>A DAMA</h3>
                            </div>
                            <div className={styles.cardimpar}>
                                <div className={styles.card}>
                                    <p>21:00</p>
                                    <h3>ÀTOOXXÁ</h3>
                                </div>                                
                            </div>
                            <div className={styles.card}>
                                <p>22:00</p>
                                <h3>Baco</h3>
                            </div>
                            <div className={styles.cardimpar}>
                                <div className={styles.card}>
                                    <p>23:00</p>
                                    <h3>Rayssa Dias</h3>
                                </div>                                
                            </div>
                            <div className={styles.card}>
                                <p>00:00</p>
                                <h3>Ludmilla</h3>
                            </div>
                            <div className={styles.cardimpar}>
                                <div className={styles.card}>
                                    <p>01:00</p>
                                    <h3>Alcione</h3>
                                </div>                                
                            </div>
                            <div className={styles.card}>
                                <p>02:00</p>
                                <h3>Damper</h3>
                            </div>
                            <div className={styles.cardimpar}>
                                <div className={styles.card}>
                                    <p>03:00</p>
                                    <h3>MartNália</h3>
                                </div>                                
                            </div>
                    </div>                    
                </div>
            </div>
        </section>
      </main>
    </>
  )
}
