import Head from 'next/head'
import styles from '@/styles/comprafinalizada.module.css'
import LoginHeaderWhite from './components/loginheaderwhite'
import MenuMobile from './components/menumobile'
import MenuMobileWhite from './components/menumobilewhite'
import Image from 'next/image'
import Verificado from "./../public/images/verificado.svg"

export default function CompraFinalizada() {
  return (
    <>
      <Head>
        <title>Compra finalizada</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
          <LoginHeaderWhite />
          <section className={styles.section}>
              <div className={styles.image}>
                  <Image id={styles.verificado} src={Verificado} alt='' />                
              </div>
              <div className={styles.text}>
                  <h2>Obrigada!</h2>
                  <h3>Pagamento efetuado. Agora retorne a tela de ingressos para acessar o seu ingresso.</h3>
                  <a href="/myticket">Meus ingressos</a>
              </div>            
          </section>
        </div>        
        <MenuMobileWhite />
      </main>
    </>
  )
}
