"use client";
import styles from "@/styles/forms.module.css";
import type {
  GetServerSidePropsContext,
  InferGetServerSidePropsType,
} from "next";
import { getCsrfToken } from "next-auth/react";
import Head from "next/head";

export default function Login({
  csrfToken,
}: InferGetServerSidePropsType<typeof getServerSideProps>) {
  return (
    <>
      <Head>
        <title>Login</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <section className={styles.section}>
          <header className={styles.header}>
            <a href="/"><img src="./images/afropunk.svg" alt="Logotipo do Afropunk"/></a>
          </header>
          <div className={styles.divBtn}>
            <a href="/">
              <button>Voltar</button>
            </a>
          </div>
          <div>
            <form
              className={styles.forms}
              method="post"
              action="/api/auth/callback/credentials"
            >
              <h1>Login</h1>
              <input name="csrfToken" type="hidden" defaultValue={csrfToken} />
              <label>
                <input name="email" type="text" placeholder="E-mail" />
              </label>
              <label>
                <input name="password" type="password" placeholder="Senha" />
              </label>
              <div className={styles.send}>
                <button type="submit">Entrar</button>
                <p>
                  Não tem conta? <a href="/register">Crie agora</a>!
                </p>
              </div>
            </form>
          </div>
        </section>
      </main>
    </>
  );
}

export async function getServerSideProps(context: GetServerSidePropsContext) {
  return {
    props: {
      csrfToken: await getCsrfToken(context),
    },
  }; 
}
